### ISSUE TITLE
created templates should include a README

### ISSUE THREAD

**Issue by purplecabbage** [adobe/create-aio-app-template#5]
Some instructions on what to do next would be helpful
- what goes where
- how do you run/test your template
- how do you publish
- how do you submit it for inclusion in our registry ( probably just a link to registry/repo which should document the process )

**Comment by shazron** [comment]
Adding the folder structure generated for reference:
```
README.md
jest.config.js
package.json
src/index.js
src/templates/index.js
src/templates/_dot.gitignore
test/index.test.js
test/jest.setup.js
.gitignore
```

**Comment by shazron** [comment]
PR #10
