### ISSUE TITLE
Not able to View the EA Form using online adobe PDF viewer

### ISSUE THREAD

**Issue by vinay2707** [adobe/create-aio-app-template#7]
**Describe the bug**

I have EA forms which includes Check box, Radio button ,Boxes ,Some Colors drawn in PDF document. 

When i tried to view this document in online adobe PDF viewer some of fields are missing.

How to resolve this issue?
What is the best way to view the EA form Document in Web Application Integration ?

Thanks 
Vinay 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shazron** [comment]
@vinay2707 why is this filed here? This repo has nothing to do with what you reported.

**Comment by vinay2707** [comment]
@shazron Can you please give me the link to rise the issue for adobe web viewer ?
